### ISSUE TITLE
Nothing happens when launching test

### ISSUE THREAD

**Issue by MoscowskyAnton** [ori-drs/plane_seg#9]
Hello!
I am trying to launch provided test on ROS Noetic, and it stops on `readpcd` step for a long time. Rviz also shows nothing, why could that happen?

**Comment by mauricefallon** [comment]
It runs for me:
> roslaunch plane_seg_ros test.launch
> roslaunch plane_seg_ros view_plane_seg.launch 

I'm not sure what to say. Perhaps you didn't compile in Release mode? Development mode is much slower

With catkin you can use this:
> catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release

![image](https://user-images.githubusercontent.com/6404227/119729967-25cf7e00-be6d-11eb-9131-dbc7755ca5b1.png)

**Comment by MoscowskyAnton** [comment]
@mauricefallon thanks for fast reply!
Build in release mode helps!
